### ISSUE TITLE
Template error on first run

### ISSUE THREAD

**Issue by javiermarcon** [reemadelsamak/crowdfunding-app#9]
Hello, in the first run, after creating the superuser, I get a template error when I try to enter the site:

Django version 3.2.20, using settings 'core.settings'
Starting development server at http://127.0.0.1:8001/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 1037, in find_library
    return parser.libraries[name]
KeyError: 'index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/javier/proyectos/django/crowdfunding-app/apps/home/views.py", line 48, in index
    html_template = loader.get_template('home/index.html')
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 1094, in load
    lib = find_library(parser, name)
  File "/home/javier/proyectos/django/crowdfunding-app/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 1039, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'index' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz

I will let you know if I find the solution.

**Comment by javiermarcon** [comment]
Sorry the solution is to clear the cache after adding the index.
